# Generated by Django 3.2.8 on 2021-10-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visualization',
            new_name='visualizations',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='description',
            field=models.TextField(default='', max_length=200, null=True),
        ),
    ]
