# Generated by Django 3.2.8 on 2021-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211026_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
