# Generated by Django 3.2.8 on 2021-10-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211026_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visualizations',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.AddField(
            model_name='publication',
            name='visualizations',
            field=models.IntegerField(default=0),
        ),
    ]
